version: '3.7'

networks:
  cdc-network:
    name: cdc-network
    driver: bridge
    external: false


services:
  cdc-postgres:
    image: debezium/postgres:13-alpine
    container_name: cdc-postgres
    hostname: cdc-postgres
    restart: always
    ports:
      - 5443:5432
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - ./cdc-postgres-data:/var/lib/postgresql/data
    networks:
      - cdc-network


  cdc-kafka:
    image: bitnami/kafka:3.4
    container_name: cdc-kafka
    hostname: cdc-kafka
    restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: a1k00yjQRaqWmAAAZv955g
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: INTERNAL://cdc-kafka:29092,CONTROLLER://cdc-kafka:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://cdc-kafka:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@cdc-kafka:29093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    networks:
      - cdc-network


  cdc-debezium-connect:
    image: debezium/connect:2.3
    container_name: cdc-debezium-connect
    hostname: cdc-debezium-connect
    restart: always
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: cdc-kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      ENABLE_DEBEZIUM_SCRIPTING: true
    links:
      - cdc-kafka
      - cdc-postgres
    networks:
      - cdc-network

  cdc-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - cdc-network


volumes:
  cdc-postgres-data:
    name: cdc-postgres-data
    driver: local